2022-02-13 01:33:09,216 INFO    MainThread:418 [internal.py:wandb_internal():91] W&B internal server running at pid: 418, started at: 2022-02-13 01:33:09.216733
2022-02-13 01:33:09,220 DEBUG   HandlerThread:418 [handler.py:handle_request():124] handle_request: run_start
2022-02-13 01:33:09,221 INFO    WriterThread:418 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220213_013308-s01ddty3/run-s01ddty3.wandb
2022-02-13 01:33:10,690 DEBUG   HandlerThread:418 [meta.py:__init__():39] meta init
2022-02-13 01:33:10,690 DEBUG   HandlerThread:418 [meta.py:__init__():53] meta init done
2022-02-13 01:33:10,690 DEBUG   HandlerThread:418 [meta.py:probe():210] probe
2022-02-13 01:33:10,697 DEBUG   HandlerThread:418 [meta.py:_setup_git():200] setup git
2022-02-13 01:33:10,723 DEBUG   HandlerThread:418 [meta.py:_setup_git():207] setup git done
2022-02-13 01:33:10,724 DEBUG   HandlerThread:418 [meta.py:_save_pip():57] save pip
2022-02-13 01:33:10,724 DEBUG   HandlerThread:418 [meta.py:_save_pip():71] save pip done
2022-02-13 01:33:10,725 DEBUG   HandlerThread:418 [meta.py:_save_conda():78] save conda
2022-02-13 01:33:13,952 DEBUG   HandlerThread:418 [meta.py:_save_conda():86] save conda done
2022-02-13 01:33:13,953 DEBUG   HandlerThread:418 [meta.py:probe():252] probe done
2022-02-13 01:33:16,354 WARNING MainThread:418 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-13 01:33:16,538 WARNING MainThread:418 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-13 01:33:16,538 ERROR   MainThread:418 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-13 01:33:16,958 INFO    WriterThread:418 [datastore.py:close():288] close: output/wandb/offline-run-20220213_013308-s01ddty3/run-s01ddty3.wandb
2022-02-13 01:33:17,226 INFO    SenderThread:418 [sender.py:finish():947] shutting down sender
2022-02-13 01:33:17,226 INFO    MainThread:418 [internal.py:handle_exit():78] Internal process exited
