2022-02-13 01:48:47,589 INFO    MainThread:1716 [internal.py:wandb_internal():91] W&B internal server running at pid: 1716, started at: 2022-02-13 01:48:47.589430
2022-02-13 01:48:47,593 INFO    WriterThread:1716 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220213_014846-vfn21y2i/run-vfn21y2i.wandb
2022-02-13 01:48:47,595 DEBUG   HandlerThread:1716 [handler.py:handle_request():124] handle_request: run_start
2022-02-13 01:48:49,103 DEBUG   HandlerThread:1716 [meta.py:__init__():39] meta init
2022-02-13 01:48:49,103 DEBUG   HandlerThread:1716 [meta.py:__init__():53] meta init done
2022-02-13 01:48:49,103 DEBUG   HandlerThread:1716 [meta.py:probe():210] probe
2022-02-13 01:48:49,109 DEBUG   HandlerThread:1716 [meta.py:_setup_git():200] setup git
2022-02-13 01:48:49,136 DEBUG   HandlerThread:1716 [meta.py:_setup_git():207] setup git done
2022-02-13 01:48:49,136 DEBUG   HandlerThread:1716 [meta.py:_save_pip():57] save pip
2022-02-13 01:48:49,137 DEBUG   HandlerThread:1716 [meta.py:_save_pip():71] save pip done
2022-02-13 01:48:49,137 DEBUG   HandlerThread:1716 [meta.py:_save_conda():78] save conda
2022-02-13 01:48:52,387 DEBUG   HandlerThread:1716 [meta.py:_save_conda():86] save conda done
2022-02-13 01:48:52,388 DEBUG   HandlerThread:1716 [meta.py:probe():252] probe done
2022-02-13 01:48:54,544 WARNING MainThread:1716 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-13 01:48:54,744 WARNING MainThread:1716 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-13 01:48:54,744 ERROR   MainThread:1716 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-13 01:48:55,394 INFO    WriterThread:1716 [datastore.py:close():288] close: output/wandb/offline-run-20220213_014846-vfn21y2i/run-vfn21y2i.wandb
2022-02-13 01:48:55,599 INFO    SenderThread:1716 [sender.py:finish():947] shutting down sender
2022-02-13 01:48:55,599 INFO    MainThread:1716 [internal.py:handle_exit():78] Internal process exited
