2022-01-06 17:06:40,059 INFO    MainThread:29098 [internal.py:wandb_internal():91] W&B internal server running at pid: 29098, started at: 2022-01-06 17:06:40.058608
2022-01-06 17:06:40,062 INFO    WriterThread:29098 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220106_170638-3db5hq03/run-3db5hq03.wandb
2022-01-06 17:06:40,066 DEBUG   HandlerThread:29098 [handler.py:handle_request():124] handle_request: run_start
2022-01-06 17:06:43,291 DEBUG   HandlerThread:29098 [meta.py:__init__():39] meta init
2022-01-06 17:06:43,291 DEBUG   HandlerThread:29098 [meta.py:__init__():53] meta init done
2022-01-06 17:06:43,291 DEBUG   HandlerThread:29098 [meta.py:probe():210] probe
2022-01-06 17:06:43,299 DEBUG   HandlerThread:29098 [meta.py:_setup_git():200] setup git
2022-01-06 17:06:43,342 DEBUG   HandlerThread:29098 [meta.py:_setup_git():207] setup git done
2022-01-06 17:06:43,343 DEBUG   HandlerThread:29098 [meta.py:_save_pip():57] save pip
2022-01-06 17:06:43,344 DEBUG   HandlerThread:29098 [meta.py:_save_pip():71] save pip done
2022-01-06 17:06:43,345 DEBUG   HandlerThread:29098 [meta.py:_save_conda():78] save conda
2022-01-06 17:06:47,013 WARNING MainThread:29098 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-01-06 17:06:47,173 WARNING MainThread:29098 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-01-06 17:06:47,174 ERROR   MainThread:29098 [internal.py:wandb_internal():150] Internal process interrupted.
2022-01-06 17:06:47,178 DEBUG   HandlerThread:29098 [meta.py:_save_conda():86] save conda done
2022-01-06 17:06:47,178 DEBUG   HandlerThread:29098 [meta.py:probe():252] probe done
2022-01-06 17:06:47,184 INFO    HandlerThread:29098 [handler.py:finish():658] shutting down handler
2022-01-06 17:06:47,513 INFO    MainThread:29098 [internal.py:handle_exit():78] Internal process exited
