2021-12-14 19:19:08,174 INFO    MainThread:15074 [internal.py:wandb_internal():91] W&B internal server running at pid: 15074, started at: 2021-12-14 19:19:08.173858
2021-12-14 19:19:08,177 INFO    WriterThread:15074 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20211214_191907-2aqql1rw/run-2aqql1rw.wandb
2021-12-14 19:19:08,178 DEBUG   HandlerThread:15074 [handler.py:handle_request():124] handle_request: run_start
2021-12-14 19:19:09,728 DEBUG   HandlerThread:15074 [meta.py:__init__():39] meta init
2021-12-14 19:19:09,728 DEBUG   HandlerThread:15074 [meta.py:__init__():53] meta init done
2021-12-14 19:19:09,728 DEBUG   HandlerThread:15074 [meta.py:probe():210] probe
2021-12-14 19:19:09,734 DEBUG   HandlerThread:15074 [meta.py:_setup_git():200] setup git
2021-12-14 19:19:09,760 DEBUG   HandlerThread:15074 [meta.py:_setup_git():207] setup git done
2021-12-14 19:19:09,760 DEBUG   HandlerThread:15074 [meta.py:_save_pip():57] save pip
2021-12-14 19:19:09,761 DEBUG   HandlerThread:15074 [meta.py:_save_pip():71] save pip done
2021-12-14 19:19:09,761 DEBUG   HandlerThread:15074 [meta.py:_save_conda():78] save conda
2021-12-14 19:19:12,898 DEBUG   HandlerThread:15074 [meta.py:_save_conda():86] save conda done
2021-12-14 19:19:12,899 DEBUG   HandlerThread:15074 [meta.py:probe():252] probe done
2021-12-14 19:19:38,789 WARNING MainThread:15074 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-12-14 19:19:38,946 WARNING MainThread:15074 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-12-14 19:19:38,946 ERROR   MainThread:15074 [internal.py:wandb_internal():150] Internal process interrupted.
2021-12-14 19:19:39,179 INFO    WriterThread:15074 [datastore.py:close():288] close: output/wandb/offline-run-20211214_191907-2aqql1rw/run-2aqql1rw.wandb
2021-12-14 19:19:39,180 INFO    HandlerThread:15074 [handler.py:finish():658] shutting down handler
2021-12-14 19:19:39,187 INFO    SenderThread:15074 [sender.py:finish():947] shutting down sender
2021-12-14 19:19:39,188 INFO    MainThread:15074 [internal.py:handle_exit():78] Internal process exited
