2022-02-07 16:50:42,016 INFO    MainThread:28074 [internal.py:wandb_internal():91] W&B internal server running at pid: 28074, started at: 2022-02-07 16:50:42.016580
2022-02-07 16:50:42,020 INFO    WriterThread:28074 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220207_165041-2wdw99ch/run-2wdw99ch.wandb
2022-02-07 16:50:42,022 DEBUG   HandlerThread:28074 [handler.py:handle_request():124] handle_request: run_start
2022-02-07 16:50:43,646 DEBUG   HandlerThread:28074 [meta.py:__init__():39] meta init
2022-02-07 16:50:43,646 DEBUG   HandlerThread:28074 [meta.py:__init__():53] meta init done
2022-02-07 16:50:43,646 DEBUG   HandlerThread:28074 [meta.py:probe():210] probe
2022-02-07 16:50:43,653 DEBUG   HandlerThread:28074 [meta.py:_setup_git():200] setup git
2022-02-07 16:50:43,681 DEBUG   HandlerThread:28074 [meta.py:_setup_git():207] setup git done
2022-02-07 16:50:43,682 DEBUG   HandlerThread:28074 [meta.py:_save_pip():57] save pip
2022-02-07 16:50:43,682 DEBUG   HandlerThread:28074 [meta.py:_save_pip():71] save pip done
2022-02-07 16:50:43,683 DEBUG   HandlerThread:28074 [meta.py:_save_conda():78] save conda
2022-02-07 16:50:46,717 DEBUG   HandlerThread:28074 [meta.py:_save_conda():86] save conda done
2022-02-07 16:50:46,717 DEBUG   HandlerThread:28074 [meta.py:probe():252] probe done
2022-02-07 16:51:01,467 WARNING MainThread:28074 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-07 16:51:01,651 WARNING MainThread:28074 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-07 16:51:01,651 ERROR   MainThread:28074 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-07 16:51:01,726 INFO    WriterThread:28074 [datastore.py:close():288] close: output/wandb/offline-run-20220207_165041-2wdw99ch/run-2wdw99ch.wandb
2022-02-07 16:51:01,739 INFO    HandlerThread:28074 [handler.py:finish():658] shutting down handler
2022-02-07 16:51:02,029 INFO    SenderThread:28074 [sender.py:finish():947] shutting down sender
2022-02-07 16:51:02,030 INFO    MainThread:28074 [internal.py:handle_exit():78] Internal process exited
