2022-01-05 13:57:46,403 INFO    MainThread:15407 [internal.py:wandb_internal():91] W&B internal server running at pid: 15407, started at: 2022-01-05 13:57:46.403460
2022-01-05 13:57:46,407 DEBUG   HandlerThread:15407 [handler.py:handle_request():124] handle_request: run_start
2022-01-05 13:57:46,408 INFO    WriterThread:15407 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220105_135745-1bdx8vt5/run-1bdx8vt5.wandb
2022-01-05 13:57:47,929 DEBUG   HandlerThread:15407 [meta.py:__init__():39] meta init
2022-01-05 13:57:47,929 DEBUG   HandlerThread:15407 [meta.py:__init__():53] meta init done
2022-01-05 13:57:47,930 DEBUG   HandlerThread:15407 [meta.py:probe():210] probe
2022-01-05 13:57:47,936 DEBUG   HandlerThread:15407 [meta.py:_setup_git():200] setup git
2022-01-05 13:57:47,961 DEBUG   HandlerThread:15407 [meta.py:_setup_git():207] setup git done
2022-01-05 13:57:47,961 DEBUG   HandlerThread:15407 [meta.py:_save_pip():57] save pip
2022-01-05 13:57:47,962 DEBUG   HandlerThread:15407 [meta.py:_save_pip():71] save pip done
2022-01-05 13:57:47,962 DEBUG   HandlerThread:15407 [meta.py:_save_conda():78] save conda
2022-01-05 13:57:51,164 DEBUG   HandlerThread:15407 [meta.py:_save_conda():86] save conda done
2022-01-05 13:57:51,164 DEBUG   HandlerThread:15407 [meta.py:probe():252] probe done
2022-01-05 13:58:09,893 WARNING MainThread:15407 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-01-05 13:58:10,141 WARNING MainThread:15407 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-01-05 13:58:10,142 ERROR   MainThread:15407 [internal.py:wandb_internal():150] Internal process interrupted.
2022-01-05 13:58:10,170 INFO    WriterThread:15407 [datastore.py:close():288] close: output/wandb/offline-run-20220105_135745-1bdx8vt5/run-1bdx8vt5.wandb
2022-01-05 13:58:10,186 INFO    HandlerThread:15407 [handler.py:finish():658] shutting down handler
2022-01-05 13:58:10,414 INFO    SenderThread:15407 [sender.py:finish():947] shutting down sender
2022-01-05 13:58:10,415 INFO    MainThread:15407 [internal.py:handle_exit():78] Internal process exited
