2022-02-13 02:01:25,171 INFO    MainThread:4040 [internal.py:wandb_internal():91] W&B internal server running at pid: 4040, started at: 2022-02-13 02:01:25.170818
2022-02-13 02:01:25,174 INFO    WriterThread:4040 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220213_020124-40rti4fv/run-40rti4fv.wandb
2022-02-13 02:01:25,176 DEBUG   HandlerThread:4040 [handler.py:handle_request():124] handle_request: run_start
2022-02-13 02:01:26,666 DEBUG   HandlerThread:4040 [meta.py:__init__():39] meta init
2022-02-13 02:01:26,666 DEBUG   HandlerThread:4040 [meta.py:__init__():53] meta init done
2022-02-13 02:01:26,666 DEBUG   HandlerThread:4040 [meta.py:probe():210] probe
2022-02-13 02:01:26,673 DEBUG   HandlerThread:4040 [meta.py:_setup_git():200] setup git
2022-02-13 02:01:26,699 DEBUG   HandlerThread:4040 [meta.py:_setup_git():207] setup git done
2022-02-13 02:01:26,699 DEBUG   HandlerThread:4040 [meta.py:_save_pip():57] save pip
2022-02-13 02:01:26,700 DEBUG   HandlerThread:4040 [meta.py:_save_pip():71] save pip done
2022-02-13 02:01:26,700 DEBUG   HandlerThread:4040 [meta.py:_save_conda():78] save conda
2022-02-13 02:01:29,880 DEBUG   HandlerThread:4040 [meta.py:_save_conda():86] save conda done
2022-02-13 02:01:29,881 DEBUG   HandlerThread:4040 [meta.py:probe():252] probe done
2022-02-13 02:02:04,541 WARNING MainThread:4040 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-13 02:02:04,748 WARNING MainThread:4040 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-13 02:02:04,748 ERROR   MainThread:4040 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-13 02:02:05,078 INFO    MainThread:4040 [internal.py:handle_exit():78] Internal process exited
